/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Remapped base tokens (used by existing components) ──────────
        'surface-0':   '#faf8ff',
        'surface-1':   '#f2f3ff',
        'surface-2':   '#eaedff',
        'surface-3':   '#e2e7ff',
        'border':      '#c2c6d6',
        'border-subtle': '#dae2fd',
        'accent':      '#0058be',
        'accent-hover':'#004395',
        'text-primary':'#131b2e',
        'text-body':   '#424754',
        'text-muted':  '#727785',
        'text-dim':    '#9ca3af',
        'success':     '#22C55E',
        'warning':     '#EAB308',
        'error':       '#EF4444',

        // ── Stitch design system tokens ──────────────────────────────────
        'surface':                    '#faf8ff',
        'surface-bright':             '#faf8ff',
        'surface-dim':                '#d2d9f4',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f2f3ff',
        'surface-container':          '#eaedff',
        'surface-container-high':     '#e2e7ff',
        'surface-container-highest':  '#dae2fd',
        'surface-variant':            '#dae2fd',
        'surface-tint':               '#005ac2',
        'on-surface':                 '#131b2e',
        'on-surface-variant':         '#424754',
        'on-background':              '#131b2e',
        'background':                 '#faf8ff',
        'primary':                    '#0058be',
        'primary-container':          '#2170e4',
        'primary-fixed':              '#d8e2ff',
        'primary-fixed-dim':          '#adc6ff',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#fefcff',
        'on-primary-fixed':           '#001a42',
        'on-primary-fixed-variant':   '#004395',
        'secondary':                  '#565e74',
        'secondary-container':        '#dae2fd',
        'secondary-fixed':            '#dae2fd',
        'secondary-fixed-dim':        '#bec6e0',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#5c647a',
        'on-secondary-fixed':         '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        'tertiary':                   '#4d5d73',
        'tertiary-container':         '#66768d',
        'tertiary-fixed':             '#d3e4fe',
        'tertiary-fixed-dim':         '#b7c8e1',
        'on-tertiary':                '#ffffff',
        'on-tertiary-container':      '#fdfcff',
        'on-tertiary-fixed':          '#0b1c30',
        'on-tertiary-fixed-variant':  '#38485d',
        'outline':                    '#727785',
        'outline-variant':            '#c2c6d6',
        'inverse-surface':            '#283044',
        'inverse-on-surface':         '#eef0ff',
        'inverse-primary':            '#adc6ff',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
      },
      fontFamily: {
        sans:     ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
        body:     ['"Inter"', 'system-ui', 'sans-serif'],
        headline: ['"Manrope"', 'system-ui', 'sans-serif'],
        label:    ['"Inter"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        card: '12px',
      },
    },
  },
  plugins: [],
}
